version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: zauberstack-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    networks:
      - nestjs

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - nestjs

networks:
  nestjs:
    driver: bridge
volumes:
  docker-nest-postgres:
    driver: local
