export enum Permission {
  Edit_Users = 'edit-users',
  Invite_Users = 'invite-users',
  Manage_Users = 'manage-users',
  Read_Subscriptions = 'read-subscriptions',
  Edit_Subscriptions = 'edit-subscriptions',
  Delete_Tasks = 'delete-tasks',
  Create_Tasks = 'create-tasks',
  Update_Tasks = 'update-tasks',
  Read_Tasks = 'read-tasks',
  Edit_Account = 'edit-account',
  Create_Tags = 'create-tags',
  Read_Tags = 'read-tags',
  Update_Tags = 'update-tags',
  Delete_Tags = 'delete-tags',
  Upload_Media = 'upload-media',
  View_Media = 'view-media',
  Delete_Media = 'delete-media',
  Walk_On_Water = 'walk-water',
}
