export const Paths = {
  SignIn: '/sign-in',
  SignUp: '/sign-up',
  ForgotPassword: '/forgot-password',
  ResetPassword: '/reset-password',
  Home: '/',
  Tasks: '/tasks',
  TaskDetail: '/tasks/:id',
  Settings: '/settings',
  Tags: '/tags',
  TagDetail: '/tags/:id',
  TeamSettings: '/settings/team',
  MagicLink: '/auth/magic-link',
  AuthCallback: '/auth/callback',
};
